version: "3.3"

services:
  gps:
    build:
      context: .
    container_name: gt06
    restart: on-failure
    ports:
      - 8090:8090

  # nginx:
  #   image: nginx:1.23.1-alpine
  #   container_name: gt06-proxy
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     - gps
  #   ports:
  #     - 8090:80
